# Use postgres/example user/password credentials
version: "3.9"
services:
  postgres:
    container_name: postgres-sql-bsn
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: Tutor
      POSTGRES_PASSWORD: 9620
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: AITutor
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
